# è¿™æ˜¯Acrylicä¸»é¢˜çš„é…ç½®æ–‡ä»¶
# å¯ä»¥å’Œæ–‡æ¡£åŒæ—¶æŸ¥çœ‹é…ç½®ï¼Œæ•ˆæœæ›´å¥½
# --------------------------------

# å›¾ç‰‡
# --------------------------------
# ç½‘ç«™å›¾æ ‡
favicon: https://tucdn.wpon.cn/2023/02/10/a43d4d587028e.png

# å¤´åƒ
avatar:
  img: https://p.zhheo.com/2023ab4befd994d9bc8e1e6a78027d517e21075402.png!cover
# å°é¢å›¾
default_img:
default_title:
default_text:

# æœç´¢
# --------------------------------
# Algolia search
algolia_search:
  enable: false
  hits:
    per_page: 6

# Local search
local_search:
  enable: false
  preload: false
  CDN:


# å¯¼èˆªæ 
# --------------------------------
nav:
  left_groups:
    enable: true
    group:
      - title: åšå®¢
        a_item:
          - text: ä¸»é¡µ
            link: https://zhheo.com/
            img: https://p.zhheo.com/20232e121c3fb2daa71897d26a515e030f49073402.png!cover_mini
            class: out
          - text: åšå®¢
            link: /
            img: https://p.zhheo.com/20234681e06b8e086aa5b15481cb89fd38c7071002.png!cover_mini
            class: out
          - text: å›¾ç‰‡åšå®¢
            link: https://plog.zhheo.com/
            img: https://p.zhheo.com/20236a16354d7c333cc7595efaee4b8c5667074602.png!cover_mini
            class: out
          - text: å¼€å‘åšå®¢
            link: https://apps.zhheo.com/
            img: https://p.zhheo.com/2023042bb31614949504f9ac59b134ce971d075802.png!cover_mini
            class: out
  logo: 
    enable: true
    class: i_class #i_class/text/img 
    custom: heoicon icon-heologo #Heo/https://xxx.com/logo.png
  fps_enable: false
  menu:
    æ–‡åº“:
      æ–‡ç« åˆ—è¡¨: /archives/ || fas fa-box-archive
      å…¨éƒ¨åˆ†ç±»: /categories/ || fas fa-cube
      å…¨éƒ¨æ ‡ç­¾: /tags/ || fas fa-tags
      å³åˆ»çŸ­æ–‡: /essay/ || fas fa-bars-staggered
    ä¸“æ :
      è®¾è®¡æŠ¥å‘Š: /tags/è®¾è®¡æŠ¥å‘Š/ || fas fa-swatchbook
      è®¾è®¡åˆ†äº«: /tags/Heocan/ || fas fa-object-group
      è®¾è®¡å·¥å…·: /tags/Sketch/ || fas fa-palette
      è§†é¢‘æ··å‰ª: /tags/æ··å‰ª/ || fas fa-scissors
    å‹é“¾:
      å‹é“¾é±¼å¡˜: /fcircle/ || fas fa-fish-fins
      å‹æƒ…é“¾æ¥: /link/ || fas fa-user-group
      å®è—åšä¸»: javascript:travelling() || fas fa-bus
    æˆ‘çš„:
      åœ¨çº¿å·¥å…·: /tlink/ || fas fa-screwdriver-wrench
      ç”µå½±æ¨è: /movies/ || fas fa-clapperboard
      å…³äºæœ¬ç«™: /about/ || fas fa-sailboat
  right_button:
    travelling: true
    random: true
    console: true

# é¡µé¢
# --------------------------------
# 404é¡µé¢
error_404:
  enable: true
  subtitle: 'è¯·å°è¯•ç«™å†…æœç´¢å¯»æ‰¾æ–‡ç« '
  background: https://tucdn.wpon.cn/2023/02/09/5fe538725e242.gif

# å³åˆ»çŸ­æ–‡ 
essay:
  enable: true
  descr: åˆ†äº«ç”Ÿæ´»çš„å°ç¡®å¹¸
  tip: ä½¿ç”¨ å³åˆ»çŸ­æ–‡é™æ€éƒ¨ç½²ç‰ˆ æ„å»º
  link: /posts/49736/
  text: å¦‚ä½•ä½¿ç”¨
  icon: fas fa-circle-chevron-right

# é¦–é¡µ
hometop:
  enable: true
  banner:
    enable: true
    class: people #people/creativity
    title_up: åˆ†äº«è®¾è®¡
    title_dn: ä¸ç§‘æŠ€ç”Ÿæ´»
    tips: ZHHEO.COM
  categoryGroup:
    enable: true
    category_list:
      - name: å¿…çœ‹ç²¾é€‰
        path: /tags/å¿…çœ‹/
        shadow: var(--heo-shadow-blue)
        class: bikan
        icon: fas fa-dove
      - name: çƒ­é—¨æ–‡ç« 
        path: /tags/çƒ­é—¨/
        shadow: var(--heo-shadow-red)
        class: remen
        icon: fas fa-burn
      - name: å®ç”¨æ•™ç¨‹
        path: /tags/æ•™ç¨‹/
        shadow: var(--heo-shadow-green)
        class: shiyong
        icon: fas fa-book
  topgroup:
    enable: true
    class: post #card/post/both
    #å¦‚æœä¸ºbothåˆ™éƒ½å¡«
    #å¦‚æœä¸ºcard
    card:
      tips: å¼ºåŠ¿å›å½’
      title: Acrylic-Promote
      bg: https://acrylic.leonus.cn/i/2023/03/04/ir6ary.webp
      link: https://blog.zhheo.com/p/671f98c8.html
      buttontext: æ›´å¤šæ¨è
      icon: fas fa-circle-plus
    #å¦‚æœä¸ºpost
    post:
      class: 
      number: 6

# å…³äºé¡µ
about:
  info:
    right:
      # - ğŸ¤–ï¸ æ•°ç çˆ±å¥½è€…
      # - ğŸ” åˆ†äº«ä¸çƒ­å¿ƒå¸®åŠ©
      # - ğŸ  æ™ºèƒ½å®¶å±…å°èƒ½æ‰‹
      # - ğŸ”¨ å¼€å‘å°èŒæ–°
    left:
      # - ä¸“ä¿®äº¤äº’è®¾è®¡ ğŸ¤
      # - è„šè¸å®åœ°è¡ŒåŠ¨æ´¾ ğŸƒ
      # - ä¸“æ”»å„ç§å›°éš¾ ğŸ§±
      # - äººç‹ è¯ä¸å¤š ğŸ’¢
  job: #å­¦ç”Ÿã€ç‹¬ç«‹å¼€å‘è€…ã€åšä¸»
  live: #ä¸­å›½ï¼ŒåŒ—äº¬å¸‚
  born: #1997
  school: #å¤§è¿å·¥ä¸šå¤§å­¦
  can: #äº§å“è®¾è®¡
  work: #UI/äº§å“
  character: #é€»è¾‘å­¦å®¶
  character2: #INTP-T
  personalities: #https://cdn.zhheo.com/public/svg/INTP-T.svg
  selfie: #https://p.zhheo.com/202352d98ec86bef3388a0152b33cf9d06ad082002.png!cover
  maxim1: #è†æ£˜ä¹‹è·¯ï¼Œ
  maxim2: #åŠˆé£æ–©æµªã€‚
  tc1: #ç„å­¦æµç”µè„‘ç–‘éš¾é—®é¢˜
  tc2: #è§£å†³ä¸“å®¶
  tc3: #è½¯ä»¶å­¦ä¹ èƒ½åŠ›
  tc4: #MAX
  uid: #'UID:125766904'
  fanjuname: #åˆºå®¢ä¼å…­ä¸ƒ
  fanjulink: #'https://www.bilibili.com/bangumi/play/ss36594/?spm_id_from=333.999.0.0'
  liketechnology: #æ•°ç ç§‘æŠ€
  liketechnologyand: #æ‰‹æœºã€ç”µè„‘è½¯ç¡¬ä»¶
  sllctitle: #ä¸ºä»€ä¹ˆå»ºç«™ï¼Ÿ
  xllc: #å†™ä¸€å†™ä½ çš„æƒ³æ³•â€¦â€¦

# æ–‡ç« 
# --------------------------------
post_meta:
  page: # é¦–é¡µ
    date_type: created # created/updated/both æ–‡ç« æ˜¾ç¤ºåˆ›ä½œæ—¥æœŸ/æ›´æ–°æ—¥æœŸ/éƒ½æ˜¾ç¤º
    date_format: date 
    categories: true # é¦–é¡µæ˜¾ç¤ºåˆ†ç±»
    tags: true # é¦–é¡µæ˜¾ç¤ºæ ‡ç­¾
    label: true # é¦–é¡µæ˜¾ç¤ºæ–‡ç« æè¿°
  post:
    date_type: both # created/updated/both æ–‡ç« æ˜¾ç¤ºåˆ›ä½œæ—¥æœŸ/æ›´æ–°æ—¥æœŸ/éƒ½æ˜¾ç¤º
    date_format: date 
    categories: true # é¦–é¡µæ˜¾ç¤ºåˆ†ç±»
    tags: true # é¦–é¡µæ˜¾ç¤ºæ ‡ç­¾
    label: true # é¦–é¡µæ˜¾ç¤ºæ–‡ç« æè¿°
  
# å­—æ•°ç»Ÿè®¡
# æ³¨æ„å®‰è£…å¯¹åº”çš„æ’ä»¶
wordcount:
  enable: false
  post_wordcount: true
  min2read: true
  total_wordcount: true

# MathJax
mathjax:
  enable: false
  per_page: false

# KaTeX
katex:
  enable: false
  per_page: false
  hide_scrollbar: true

# ç‰ˆæƒ
copyright:
  enable: true
  link: /cc/
  license: CC BY-NC-SA 4.0
  license_url: https://creativecommons.org/licenses/by-nc-sa/4.0/
  
# ç›¸å…³æ–‡ç« 
related_post:
  enable: true

# æ–‡ç« åº•éƒ¨å·¥å…·
ptool:
  enable: true

# æ‰“èµ
reward:
  enable: true
  QR_code:
    - img: https://cdn.staticaly.com/gh/gtwxxh666/pic@main/1/wechat.png
      link:
      text: å¾®ä¿¡
    - img: https://cdn.staticaly.com/gh/gtwxxh666/pic@main/1/alipay.png
      link:
      text: æ”¯ä»˜å®

# è¯„è®ºç³»ç»Ÿ
# --------------------------------
comments:
  use: Twikoo # Waline/Twikoo/Artalk
  text: true # åœ¨æŒ‰é’®æ—è¾¹æ˜¾ç¤ºè¯„è®ºåç§°
  # lazyload: å½“è¯„è®ºè¿›å…¥æµè§ˆå™¨è§†é‡æ—¶ï¼Œè¯„è®ºç³»ç»Ÿå°†è¢«åŠ è½½ã€‚
  lazyload: false
  count: false # é¡¶éƒ¨å›¾æ˜¾ç¤ºè¯„è®ºæ•°
  card_post_count: false # é¦–é¡µæ˜¾ç¤ºè¯„è®ºæ•°

# waline 
# https://waline.js.org/
waline:
  serverURL: # Waline server address url
  bg: # waline background
  pageview: false
  option:

# Twikoo
# https://github.com/imaegoo/twikoo
twikoo:
  envId: 
  region:
  visitor: false
  option:

# Artalk
# https://artalk.js.org/guide/frontend/config.html
artalk:
  server:
  site:
  visitor: false
  option:

# åº•éƒ¨
# --------------------------------
footer:
  footer_icons:
    enable: true
    left:
      - icon: fa-solid fa-compass
        link: https://www.marcus233.top/
        desrc: ä¸ªäººä¸»é¡µ
        class: out
      - icon: fa-brands fa-qq
        link: https://res.abeim.cn/api/qq/?qq=3105950984
        desrc: è”ç³»QQ
        class: out
      - icon: fa-brands fa-weixin
        link: /wechat/
        desrc: è”ç³»å¾®ä¿¡
        class: in
      - icon: fa-solid fa-envelope
        link: mailto:marcus@marcus233.top
        desrc: å‘é€é‚®ä»¶
        class: out
    right:
      - icon: fa-brands fa-github
        link: https://github.com/Marcusyyds
        desrc: Githubä¸»é¡µ
        class: out
      - icon: fa-brands fa-bilibili
        link: https://space.bilibili.com/1024450661
        desrc: å“”å“©å“”å“©ä¸»é¡µ
        class: out
      - icon: fa-solid fa-star
        link: /stars/
        desrc: è—å®é˜
        class: in
      - icon: fa-solid fa-comment
        link: /message/
        desrc: ç•™è¨€
        class: in
  footer_logo:
    enable: true
    url: https://bu.dusays.com/2023/03/03/6401a7960c0fb.webp
  footer_group:
    enable: true
    footer_group_link:
      - group_title: è½¯ä»¶
        footer_links: 
          - text: æ•²æœ¨é±¼
            link: /stars/
            class: in
          - text: è½»èŠ‚é£Ÿ
            link: /sentence/
            class: in
          - text: DelSpace3
            link: /zone/
            class: in
          - text: æ¯”ä¾‹è®¡
            link: /fcircle/
            class: in
      - group_title: äº§å“
        footer_links: 
          - text: è®¾è®¡æŠ¥å‘Š
            link: /about/
            class: in
          - text: ä¼˜è´¨æŠ¥å‘Š
            link: /atom.xml
            class: in
      - group_title: è®¾è®¡
        footer_links: 
          - text: Heocan
            link: /categories/åšå®¢ç›¸å…³
            class: in
          - text: Sketch
            link: /categories/ç”Ÿæ´»ç‚¹æ»´
            class: in 
          - text: è®¾è®¡æŠ¥å‘Š
            link: /categories/èµ„æºåˆ†äº«
            class: in
          - text: Photoshop
            link: /categories/å­¦ä¹ ç¬”è®°
            class: in
      - group_title: å¼€å‘
        footer_links: 
          - text: Hexoé­”æ”¹
            link: /categories/åšå®¢ç›¸å…³
            class: in
          - text: Swiftå¼€å‘
            link: /categories/ç”Ÿæ´»ç‚¹æ»´
            class: in 
          - text: ç½‘é¡µå‰ç«¯
            link: /categories/èµ„æºåˆ†äº«
            class: in
      - group_title: ç”Ÿæ´»
        footer_links: 
          - text: éŸ³ä¹æ¦œå•
            link: /music/
            class: in
          - text: æˆ‘çš„ç”µå½±
            link: /categories/ç”Ÿæ´»ç‚¹æ»´
            class: in 
          - text: è¯»ä¹¦ç¬”è®°
            link: /categories/èµ„æºåˆ†äº«
            class: in
          - text: è§†é¢‘å‰ªè¾‘
            link: /categories/å­¦ä¹ ç¬”è®°
            class: in
      - group_title: å¯¼èˆª
        footer_links: 
          - text: å³åˆ»çŸ­æ–‡
            link: /categories/åšå®¢ç›¸å…³
            class: in
          - text: åœ¨çº¿å·¥å…·
            link: /categories/ç”Ÿæ´»ç‚¹æ»´
            class: in 
          - text: å‹é“¾æ–‡ç« 
            link: /categories/èµ„æºåˆ†äº«
            class: in
      - group_title: æœåŠ¡
        footer_links: 
          - text: 51laç»Ÿè®¡
            link: /categories/åšå®¢ç›¸å…³
            class: in
          - text: BlogFinder
            link: /categories/ç”Ÿæ´»ç‚¹æ»´
            class: in 
          - text: åå¹´ä¹‹çº¦
            link: /categories/èµ„æºåˆ†äº«
            class: in
      - group_title: åè®®
        footer_links: 
          - text: éšç§åè®®
            link: /categories/åšå®¢ç›¸å…³
            class: in
          - text: Cookies
            link: /categories/ç”Ÿæ´»ç‚¹æ»´
            class: in 
          - text: ç‰ˆæƒåè®®
            link: /categories/èµ„æºåˆ†äº«
            class: in
  icp: äº¬ICPå¤‡1905135å·

# å°å·¥å…·
# --------------------------------
#å¹¿å‘Š
# ad:
#   index:
#   aside:
#   post:

# åŠ è½½åŠ¨ç”»
loading: 
  enable: true

# æ‰‹æœºè¾¹æ  
sidebar: 
  list_group: true
  tag: true

# ä¸­æ§å°
console:
  comment: true
  tag: true
  archives: true 

# å›¾ç‰‡æ”¾å¤§
# fancybox
# http://fancyapps.com/fancybox/3/
fancybox: true

# æ ‡ç­¾å¤–æŒ‚
mermaid:
  enable: false
  # ä¸»é¢˜: default/forest/dark/neutral
  theme:
    light: default
    dark: dark

# Note
note:
  style: flat
  icons: true
  border_radius: 3
  light_bg_offset: 0

# ç¾åŒ–
# --------------------------------
# ä¸»é¢˜è‰²
# å†™HEXæˆ–è€…RGB
theme_color:
  enable: true
  main: "#425AEF"
#   paginator: "#00c4b6"
  button_hover: "#425AEF"
#   text_selection: "#00c4b6"
  link_color: "#425AEF"
#   meta_color: "#858585"
#   hr_color: "#A4D8FA"
#   code_foreground: "#F47466"
#   code_background: "rgba(27, 31, 35, .05)"
#   toc_color: "#00c4b6"
#   blockquote_padding_color: "#49b1f5"
#   blockquote_background_color: "#49b1f5"
#   scrollbar_color: "#49b1f5"
#   meta_theme_color_light: "ffffff"
#   meta_theme_color_dark: "#0d0d0d"

# æ˜¾ç¤ºæ¨¡å¼
# light/dark
display_mode: light

# ä¾§è¾¹æ 
# --------------------------------
aside:
  enable: true
  button: true
  mobile: true # æ‰‹æœºæ˜¾ç¤º
  position: right # å·¦è¾¹å³è¾¹ right/left
  card_author:
    enable: true
    description:
    button:
      enable: true
      icon: fab fa-github
      text: Follow Me
      link: https://github.com/xxxxxx
  card_weixin:
    enable: true
  card_recent_post:
    enable: false
    limit: 5 # è¾“å…¥0å…¨æ˜¾ç¤º
    sort: date # æ˜¾ç¤ºå‘å¸ƒæ—¥æœŸ/æ›´æ–°æ—¥æœŸ
    sort_order: 
  card_all_info:
    enable: true
    post_count: true
    runtime: true
    word_count: false


# è®¿é—®äººæ•¸
busuanzi:
  site_uv: true
  site_pv: true
  page_pv: true

# è¿è¡Œæ—¶é—´
runtimeshow:
  enable: true
  publish_date: 

# å³ä¸‹è§’æŒ‰é’®
# --------------------------------
# ç®€ä½“ç¹ä½“åˆ‡æ¢
translate:
  enable: true
  default: ç¹
  defaultEncoding: 2
  translateDelay: 0
  msgToTraditionalChinese: 'ç¹'
  msgToSimplifiedChinese: 'ç°¡'

# é˜…è¯»æ¨¡å¼
readmode: false

# æ·±è‰²æ¨¡å¼
darkmode:
  enable: true
  button: true
  # è‡ªåŠ¨åˆ‡æ¢æš—/äº®æ¨¡å¼
  # 1ï¼š æŒ‰ç…§ç³»ç»Ÿè®¾ç½®ï¼Œå¦‚æœç³»ç»Ÿä¸æ”¯æŒæ·±è‰²æ¨¡å¼ï¼Œå®ƒå°†åœ¨ä¸‹åˆ 6 ç‚¹åˆ°æ—©ä¸Š 6 ç‚¹ä¹‹é—´åˆ‡æ¢æ·±è‰²æ¨¡å¼
  # 2ï¼š åœ¨ä¸‹åˆ 6 ç‚¹åˆ°æ—©ä¸Š 6 ç‚¹ä¹‹é—´åˆ‡æ¢é»‘æš—æ¨¡å¼
  autoChangeMode: 1

rightside_item_order:
  enable: false
  hide: 
  show: 

# å…¶ä»–
# --------------------------------
# Pjax
# å®ƒå¯èƒ½åŒ…å«é”™è¯¯å’Œä¸ç¨³å®š
# https://github.com/MoOx/pjax
pjax:
  enable: true
  exclude:
    # - xxxx
    # - xxxx

# Aplayer
aplayerInject:
  enable: true
  per_page: true

# å¼¹çª—
# https://github.com/polonel/SnackBar
# ä½ç½® top-left / top-center / top-right / bottom-left / bottom-center / bottom-right
snackbar:
  enable: true
  position: top-center
  bg_light: '#49b1f5' 
  bg_dark: '#1f1f1f' 

# https://instant.page/
# é¢„åŠ è½½
instantpage: true

# ä¸­è‹±æ–‡é—´åŠ ç©ºæ ¼
pangu:
  enable: false
  field: site # site/post

# å›¾ç‰‡æ‡’åŠ è½½
# https://github.com/verlok/vanilla-lazyload
lazyload:
  enable: false
  field: site # site/post
  placeholder:
  blur: false

# PWA
# https://github.com/JLHwung/hexo-offline
# pwa:
#   enable: false
#   manifest: /pwa/manifest.json
#   apple_touch_icon: /pwa/apple-touch-icon.png
#   favicon_32_32: /pwa/32.png
#   favicon_16_16: /pwa/16.png
#   mask_icon: /pwa/safari-pinned-tab.svg


Open_Graph_meta: true

css_prefix: true

# ä»£ç å¼•å…¥
# --------------------------------
inject:
  head:
    # - <link rel="stylesheet" href="/xxx.css">
    # é€šå¸¸è¿™é‡Œå†™CSS
  bottom:
    # - <script src="/js/xxx.js"></script>
    # é€šå¸¸è¿™é‡Œå†™JS
    - <script type="text/javascript" src="https://cdn1.tianli0.top/npm/jquery@latest/dist/jquery.min.js"></script>
    - <script src="//cdn.bootcss.com/pace/1.0.2/pace.min.js"></script>
    - <script src="/js/blogex.js"></script>
    - <script src="/js/black.js"></script>
    - <script src="/js/xh.js"></script>
    - <script src="/js/nav.js"></script>
    - <script src="/js/bblist.js"></script>
    - <script data-pjax src="https://npm.elemecdn.com/anzhiyu-blog@1.1.6/js/swiper.min.js"></script>
    - <script async data-pjax src="/js/jkdw.js"></script>
    - <script async data-pjax src="/js/waterfall.js"></script>
    - <script src="/js/nav2.js"></script>
    - <script src="/js/heo.js"></script>
    - <script src="/js/hidescrollbar.js"></script>
    - <script src="/js/rightmenu.js"></script>
    - <script src="/js/sayhi.js"></script>
    - <script async data-pjax src="/js/anzhiyu.js"></script>
    - <script async data-pjax src="/js/anzhiyufunction.js"></script>
    - <script async src="/js/anzhiyuOnlyOne.js"></script>
    - <script src="/heo/random.js"></script>
    

# CDN
# --------------------------------
CDN:
  internal_provider: local

  # ç¬¬ä¸‰æ–¹CDN
  # moezz/local/jsdelivr/unpkg/cdnjs/custom
  third_party_provider: jsdelivr

  version: false
  # å®ä¾‹: https://cdn.staticfile.org/${cdnjs_name}/${version}/${min_cdnjs_file}
  custom_format:

  option:
    # main_css:
    countup_js: /js/countup.js
    # main:
    # utils:
    # translate:
    # local_search:
    # algolia_js:
    # algolia_search_v4:
    # instantsearch_v4:
    # pjax:
    twikoo: https://cdn2.tianli0.top/gh/zhheo/twikoo@dev/dist/twikoo.all.min.js
    # waline_js:
    # waline_css:
    # mathjax:
    # katex:
    # katex_copytex:
    # mermaid:
    # lazyload:
    # instantpage:
    # typed:
    # pangu:
    # fancybox_css_v4:
    # fancybox_v4:
    # snackbar_css:
    # snackbar:
    # activate_power_mode:
    fontawesomeV6: https://cdn1.tianli0.top/npm/@fortawesome/fontawesome-free/css/all.min.css
    aplayer_css: https://lf6-cdn-tos.bytecdntp.com/cdn/expire-1-M/aplayer/1.10.1/APlayer.min.css
    aplayer_js: https://lf26-cdn-tos.bytecdntp.com/cdn/expire-1-M/aplayer/1.10.1/APlayer.min.js
    meting_js: https://cdn1.tianli0.top/gh/hexo-theme-Acrylic/JS-Acrylic@main/Meting.js
    # artalk_js:
    # artalk_css:
