# æ¬¢è¿ä½¿ç”¨Acrylicä¸»é¢˜!ğŸ‰
# Welcome to use theme of Acrylic!ğŸ‰
# æ–‡æ¡£: https://pro.Acrylic.org.cn/
# docs: https://docs.pro.Acrylic.org.cn/
# äº¤æµç¾¤: 649565726
# è¿™æ˜¯Devç‰ˆ!
# -------------------------------------

# å›¾ç‰‡
# --------------------------------

# ç½‘ç«™å›¾æ ‡ (favicon)
favicon: https://tucdn.wpon.cn/2023/02/10/a43d4d587028e.png

# å¤´åƒ (avatar)
avatar:
  img: https://p.zhheo.com/2023ab4befd994d9bc8e1e6a78027d517e21075402.png!cover

# é»˜è®¤ä¿¡æ¯ (default)
default_img: https://img1.acrylic.org.cn/2023/04/16/643b6a036a2cb.webp
default_title: æ²¡æœ‰é…ç½®æ
default_text: æ²¡æœ‰é…ç½®æ

# æœç´¢ (search)
# --------------------------------

# Algolia æœç´¢ (Algolia search)
algolia_search:
  enable: false
  hits:
    per_page: 6

# æœ¬åœ°æœç´¢ (Local search)
local_search:
  enable: false
  preload: false
  CDN:


# å¯¼èˆªæ  (nav)
# --------------------------------
nav:
  group_icon: fas fa-grip-vertical
  left_groups:
    enable: true
    group:
      - title: åšå®¢
        a_item:
          - text: ä¸»é¡µ
            link: https://zhheo.com/
            img: https://p.zhheo.com/20232e121c3fb2daa71897d26a515e030f49073402.png!cover_mini
            class: out
          - text: åšå®¢
            link: /
            img: https://p.zhheo.com/20234681e06b8e086aa5b15481cb89fd38c7071002.png!cover_mini
            class: out
          - text: å›¾ç‰‡åšå®¢
            link: https://plog.zhheo.com/
            img: https://p.zhheo.com/20236a16354d7c333cc7595efaee4b8c5667074602.png!cover_mini
            class: out
          - text: å¼€å‘åšå®¢
            link: https://apps.zhheo.com/
            img: https://p.zhheo.com/2023042bb31614949504f9ac59b134ce971d075802.png!cover_mini
            class: out
  logo: 
    enable: true
    class: i_class #i_class/text/img i_classä¸ºiconå›¾æ ‡,textä¸ºæ–‡å­—,imgä¸ºå›¾ç‰‡
    custom: heofont icon-heologo # heofont icon-heologo / Heo / https://xxx.com/logo.png/
  fps_enable: false
  menu:
    æ–‡åº“:
      æ–‡ç« åˆ—è¡¨: /archives/ || fas fa-box-archive
      å…¨éƒ¨åˆ†ç±»: /categories/ || fas fa-cube
      å…¨éƒ¨æ ‡ç­¾: /tags/ || fas fa-tags
      å³åˆ»çŸ­æ–‡: /essay/ || fas fa-bars-staggered
    ä¸“æ :
      è®¾è®¡æŠ¥å‘Š: /tags/è®¾è®¡æŠ¥å‘Š/ || fas fa-swatchbook
      è®¾è®¡åˆ†äº«: /tags/Heocan/ || fas fa-object-group
      è®¾è®¡å·¥å…·: /tags/Sketch/ || fas fa-palette
      è§†é¢‘æ··å‰ª: /tags/æ··å‰ª/ || fas fa-scissors
    å‹é“¾:
      å‹é“¾é±¼å¡˜: /fcircle/ || fas fa-fish-fins
      å‹æƒ…é“¾æ¥: /link/ || fas fa-user-group
      å®è—åšä¸»: javascript:travelling() || fas fa-bus
    æˆ‘çš„:
      æˆ‘çš„è£…å¤‡: /equipment/ || fa-fw heofont icon-bijiben
      åœ¨çº¿å·¥å…·: /tlink/ || fas fa-screwdriver-wrench
      å…³äºæœ¬ç«™: /about/ || fas fa-sailboat
  right_button:
    travelling:
      enable: true
      icon: fas fa-train-subway
    random:
      enable: true
      icon: fas fa-shuffle
    search: fas fa-magnifying-glass
    console:
      enable: true
      icon: fas fa-bars-progress
    totop: fas fa-arrow-up

# é¡µé¢ (page)
# --------------------------------
# 404é¡µé¢ (404 page)
error_404:
  enable: true
  subtitle: 'è¯·å°è¯•ç«™å†…æœç´¢å¯»æ‰¾æ–‡ç« '
  background: https://img1.acrylic.org.cn/2023/04/16/643b6a036a2cb.webp

# å³åˆ»çŸ­æ–‡ (essay page)
essay:
  enable: true
  descr: åˆ†äº«ç”Ÿæ´»çš„å°ç¡®å¹¸
  tip: ä½¿ç”¨ å³åˆ»çŸ­æ–‡é™æ€éƒ¨ç½²ç‰ˆ æ„å»º
  link: /posts/49736/
  text: å¦‚ä½•ä½¿ç”¨
  icon: fas fa-circle-chevron-right

# memosçŸ­æ–‡ (memos page)
memos:
  enable: true
  descr: åˆ†äº«ç”Ÿæ´»çš„å°ç¡®å¹¸
  tip: ä½¿ç”¨ memos æ„å»º
  link: /posts/49736/
  text: å¦‚ä½•ä½¿ç”¨
  icon: fas fa-circle-chevron-right
  api: https://memos.acrylic.org.cn/api/memo?creatorId=1&tag=è¯´è¯´&limit=30

# æœ‹å‹åœˆfcricle (fcricle page)
fcricle:
  enable: true
  descr: å®ç‰©è£…å¤‡æ¨è
  tip: å¥½ç‰©
  link: /posts/49736/
  text: å¦‚ä½•ä½¿ç”¨
  icon: fas fa-circle-chevron-right
  api: https://fcircle.acrylic.org.cn/

# è£…å¤‡equipment (equipment page)
equipment:
  enable: true
  descr: å®ç‰©è£…å¤‡æ¨è
  tip: è·Ÿ å¼ æ´ªHeo ä¸€èµ·äº«å—ç§‘æŠ€å¸¦æ¥çš„ä¹è¶£
  link: /posts/49736/
  text: å¦‚ä½•ä½¿ç”¨
  icon: fas fa-circle-chevron-right

# å‹è”é¡µé¢ (link page)
link:
  enable: true
  banner: true
  ramdon_post: true
  flink_posts: false #æœªå¼€å‘å®Œæˆ
  add_flink: false #æœªå¼€å‘å®Œæˆ
# å…³äºé¡µé¢ (about page)
about:
  info:
    right:
      - ğŸ¤–ï¸ æ•°ç çˆ±å¥½è€…
      - ğŸ” åˆ†äº«ä¸çƒ­å¿ƒå¸®åŠ©
      - ğŸ  æ™ºèƒ½å®¶å±…å°èƒ½æ‰‹
      - ğŸ”¨ å¼€å‘å°èŒæ–°
    left:
      - ä¸“ä¿®äº¤äº’è®¾è®¡ ğŸ¤
      - è„šè¸å®åœ°è¡ŒåŠ¨æ´¾ ğŸƒ
      - ä¸“æ”»å„ç§å›°éš¾ ğŸ§±
      - äººç‹ è¯ä¸å¤š ğŸ’¢
  job: å­¦ç”Ÿã€ç‹¬ç«‹å¼€å‘è€…ã€åšä¸»
  live: ä¸­å›½ï¼ŒåŒ—äº¬å¸‚
  born: 1997
  school: å¤§è¿å·¥ä¸šå¤§å­¦
  can: äº§å“è®¾è®¡
  work: UI/äº§å“
  character: é€»è¾‘å­¦å®¶
  character2: INTP-T
  personalities: https://cdn.zhheo.com/public/svg/INTP-T.svg
  selfie: https://p.zhheo.com/202352d98ec86bef3388a0152b33cf9d06ad082002.png!cover
  maxim1: è†æ£˜ä¹‹è·¯ï¼Œ
  maxim2: åŠˆé£æ–©æµªã€‚
  tc1: ç„å­¦æµç”µè„‘ç–‘éš¾é—®é¢˜
  tc2: è§£å†³ä¸“å®¶
  tc3: è½¯ä»¶å­¦ä¹ èƒ½åŠ›
  tc4: MAX
  uid: 'UID:125766904'
  fanjuname: åˆºå®¢ä¼å…­ä¸ƒ
  fanjulink: 'https://www.bilibili.com/bangumi/play/ss36594/?spm_id_from=333.999.0.0'
  liketechnology: æ•°ç ç§‘æŠ€
  liketechnologyand: æ‰‹æœºã€ç”µè„‘è½¯ç¡¬ä»¶
  sllctitle: ä¸ºä»€ä¹ˆå»ºç«™ï¼Ÿ
  xllc: å†™ä¸€å†™ä½ çš„æƒ³æ³•â€¦â€¦

# æ–‡ç«  (post)
# --------------------------------
post_meta:
  page: # é¦–é¡µ
    date_type: created # created/updated/both æ–‡ç« æ˜¾ç¤ºåˆ›ä½œæ—¥æœŸ/æ›´æ–°æ—¥æœŸ/éƒ½æ˜¾ç¤º
    date_format: relative 
    categories: true # é¦–é¡µæ˜¾ç¤ºåˆ†ç±»
    tags: true # é¦–é¡µæ˜¾ç¤ºæ ‡ç­¾
    label: true # é¦–é¡µæ˜¾ç¤ºæ–‡ç« æè¿°
  post:
    date_type: both # created/updated/both æ–‡ç« æ˜¾ç¤ºåˆ›ä½œæ—¥æœŸ/æ›´æ–°æ—¥æœŸ/éƒ½æ˜¾ç¤º
    date_format: date 
    categories: true # é¦–é¡µæ˜¾ç¤ºåˆ†ç±»
    tags: true # é¦–é¡µæ˜¾ç¤ºæ ‡ç­¾
    label: true # é¦–é¡µæ˜¾ç¤ºæ–‡ç« æè¿°
  location: æˆéƒ½ #åœ°ç‚¹

# # æ–‡ç« é¡¶éƒ¨aiæ‘˜è¦
# post_head_ai_description:
#   enable: true
#   gptName: Heo
#   mode: tianli # é»˜è®¤æ¨¡å¼ å¯é€‰å€¼: tianli/local
#   switchBtn: false # å¯ä»¥é…ç½®æ˜¯å¦æ˜¾ç¤ºåˆ‡æ¢æŒ‰é’® ä»¥åˆ‡æ¢tianli/local
#   btnLink: https://afdian.net/item/886a79d4db6711eda42a52540025c377
#   randomNum: 3 # æŒ‰é’®æœ€å¤§çš„éšæœºæ¬¡æ•°ï¼Œä¹Ÿå°±æ˜¯ä¸€ç¯‡æ–‡ç« æœ€å¤§éšæœºå‡ºæ¥å‡ ç§
#   basicWordCount: 1000 # æœ€ä½è·å–å­—ç¬¦æ•°, æœ€å°1000, æœ€å¤§1999
#   key: SZLhZo3TjRN7GZ9JiRFa
#   Referer: https://xx.xx/

theme_color:
  enable: true
  mode: img2color # online/local(æœªå®Œæˆ)
  api: https://api-marcusyyds.vercel.app/v1/img2color

# å­—æ•°ç»Ÿè®¡ (wordcount)
# æ³¨æ„å®‰è£…å¯¹åº”çš„æ’ä»¶
wordcount:
  enable: false
  post_wordcount: true
  min2read: true
  total_wordcount: true

# æ•°å­¦å…¬å¼
# MathJax
mathjax:
  enable: false
  per_page: false

# KaTeX
katex:
  enable: false
  per_page: false
  hide_scrollbar: true

# ç‰ˆæƒ (copyright)
copyright:
  enable: true
  link: /cc/
  license: CC BY-NC-SA 4.0
  short: cc
  license_url: https://creativecommons.org/licenses/by-nc-sa/4.0/
  
# ç›¸å…³æ–‡ç«  (related post)
related_post:
  enable: true

# æ–‡ç«  ptool (ptool)
ptool:
  enable: true

# æ‰“èµ (reward)
reward:
  enable: true
  QR_code:
    - img: https://cdn.staticaly.com/gh/gtwxxh666/pic@main/1/wechat.png
      link:
      text: å¾®ä¿¡
    - img: https://cdn.staticaly.com/gh/gtwxxh666/pic@main/1/alipay.png
      link:
      text: æ”¯ä»˜å®

# è¯„è®º (comments)
# --------------------------------
comments:
  use: Twikoo # Waline/Twikoo/Artalk
  text: true # åœ¨æŒ‰é’®æ—è¾¹æ˜¾ç¤ºè¯„è®ºåç§°
  # lazyload: å½“è¯„è®ºè¿›å…¥æµè§ˆå™¨è§†é‡æ—¶ï¼Œè¯„è®ºç³»ç»Ÿå°†è¢«åŠ è½½ã€‚
  lazyload: false
  count: true # é¡¶éƒ¨å›¾æ˜¾ç¤ºè¯„è®ºæ•°
  card_post_count: false # é¦–é¡µæ˜¾ç¤ºè¯„è®ºæ•°

# waline 
# https://waline.js.org/
waline:
  serverURL: # Waline server address url
  bg: # waline background
  pageview: false
  option:

# Twikoo
# https://github.com/imaegoo/twikoo
twikoo:
  envId: https://t.pro.acrylic.org.cn/
  region: 
  visitor: false
  option:

# Artalk
# https://artalk.js.org/guide/frontend/config.html
artalk:
  server:
  site:
  visitor: false
  option:

# é¦–é¡µ hometop (hometop)
hometop:
  enable: true
  banner:
    enable: true
    class: creativity #people(äººæ½®æ±¹æ¶Œ)/creativity(åˆ›é€ åŠ›)
    title_up: åˆ†äº«è®¾è®¡
    title_dn: ä¸ç§‘æŠ€ç”Ÿæ´»
    tips: ZHHEO.COM
  categoryGroup:
    enable: true
    category_list:
      - name: å¿…çœ‹ç²¾é€‰
        path: /tags/å¿…çœ‹/
        shadow: var(--heo-shadow-blue)
        class: bikan
        icon: fas fa-dove
      - name: çƒ­é—¨æ–‡ç« 
        path: /tags/çƒ­é—¨/
        shadow: var(--heo-shadow-red)
        class: remen
        icon: fas fa-burn
      - name: å®ç”¨æ•™ç¨‹
        path: /tags/æ•™ç¨‹/
        shadow: var(--heo-shadow-green)
        class: shiyong
        icon: fas fa-book
  topgroup:
    enable: true
    class: both #card/post/both
    #å¦‚æœä¸ºcard/both
    card:
      tips: å¼ºåŠ¿å›å½’
      title: Acrylic-Promote
      bg: https://img1.acrylic.org.cn/2023/04/16/643b6a036a2cb.webp
      link: https://blog.zhheo.com/p/671f98c8.html
      buttontext: æ›´å¤šæ¨è
      icon: fas fa-circle-plus
      color: #0E57D5
      text_color: #ffffff # é»˜è®¤ç™½è‰²

# é¡µè„š (footer)
# --------------------------------
footer:
  bar:
    enable: true
    logo: heofont icon-heologo
    desc: æœ€æ–°è®¾è®¡ä¸ç§‘æŠ€çš„æ–‡ç« 
    link: /
    button_text: äº†è§£æ›´å¤š
  footer_icons:
    enable: true
    left:
      - icon: fa-solid fa-compass
        link: https://www.marcus233.top/
        desrc: ä¸ªäººä¸»é¡µ
        class: out
      - icon: fa-brands fa-qq
        link: https://res.abeim.cn/api/qq/?qq=3105950984
        desrc: è”ç³»QQ
        class: out
      - icon: fa-brands fa-weixin
        link: /wechat/
        desrc: è”ç³»å¾®ä¿¡
        class: in
      - icon: fa-solid fa-envelope
        link: mailto:marcus@marcus233.top
        desrc: å‘é€é‚®ä»¶
        class: out
    right:
      - icon: fa-brands fa-github
        link: https://github.com/Marcusyyds
        desrc: Githubä¸»é¡µ
        class: out
      - icon: fa-brands fa-bilibili
        link: https://space.bilibili.com/1024450661
        desrc: å“”å“©å“”å“©ä¸»é¡µ
        class: out
      - icon: fa-solid fa-star
        link: /stars/
        desrc: è—å®é˜
        class: in
      - icon: fa-solid fa-comment
        link: /message/
        desrc: ç•™è¨€
        class: in
  footer_logo:
    enable: true
    url: https://bu.dusays.com/2023/03/03/6401a7960c0fb.webp
  footer_group:
    enable: true
    footer_group_link:
      - group_title: è½¯ä»¶
        footer_links: 
          - text: æ•²æœ¨é±¼
            link: /stars/
            class: in
          - text: è½»èŠ‚é£Ÿ
            link: /sentence/
            class: in
          - text: DelSpace3
            link: /zone/
            class: in
          - text: æ¯”ä¾‹è®¡
            link: /fcircle/
            class: in
      - group_title: äº§å“
        footer_links: 
          - text: è®¾è®¡æŠ¥å‘Š
            link: /about/
            class: in
          - text: ä¼˜è´¨æŠ¥å‘Š
            link: /atom.xml
            class: in
      - group_title: è®¾è®¡
        footer_links: 
          - text: Heocan
            link: /categories/åšå®¢ç›¸å…³
            class: in
          - text: Sketch
            link: /categories/ç”Ÿæ´»ç‚¹æ»´
            class: in 
          - text: è®¾è®¡æŠ¥å‘Š
            link: /categories/èµ„æºåˆ†äº«
            class: in
          - text: Photoshop
            link: /categories/å­¦ä¹ ç¬”è®°
            class: in
      - group_title: å¼€å‘
        footer_links: 
          - text: Hexoé­”æ”¹
            link: /categories/åšå®¢ç›¸å…³
            class: in
          - text: Swiftå¼€å‘
            link: /categories/ç”Ÿæ´»ç‚¹æ»´
            class: in 
          - text: ç½‘é¡µå‰ç«¯
            link: /categories/èµ„æºåˆ†äº«
            class: in
      - group_title: ç”Ÿæ´»
        footer_links: 
          - text: éŸ³ä¹æ¦œå•
            link: /music/
            class: in
          - text: æˆ‘çš„ç”µå½±
            link: /categories/ç”Ÿæ´»ç‚¹æ»´
            class: in 
          - text: è¯»ä¹¦ç¬”è®°
            link: /categories/èµ„æºåˆ†äº«
            class: in
          - text: è§†é¢‘å‰ªè¾‘
            link: /categories/å­¦ä¹ ç¬”è®°
            class: in
      - group_title: å¯¼èˆª
        footer_links: 
          - text: å³åˆ»çŸ­æ–‡
            link: /categories/åšå®¢ç›¸å…³
            class: in
          - text: åœ¨çº¿å·¥å…·
            link: /categories/ç”Ÿæ´»ç‚¹æ»´
            class: in 
          - text: å‹é“¾æ–‡ç« 
            link: /categories/èµ„æºåˆ†äº«
            class: in
      - group_title: æœåŠ¡
        footer_links: 
          - text: 51laç»Ÿè®¡
            link: /categories/åšå®¢ç›¸å…³
            class: in
          - text: BlogFinder
            link: /categories/ç”Ÿæ´»ç‚¹æ»´
            class: in 
          - text: åå¹´ä¹‹çº¦
            link: /categories/èµ„æºåˆ†äº«
            class: in
      - group_title: åè®®
        footer_links: 
          - text: éšç§åè®®
            link: /categories/åšå®¢ç›¸å…³
            class: in
          - text: Cookies
            link: /categories/ç”Ÿæ´»ç‚¹æ»´
            class: in 
          - text: ç‰ˆæƒåè®®
            link: /categories/èµ„æºåˆ†äº«
            class: in
  footer_friend_links:
    enable: true
  footer_bottom:
    copyright:
      enable: true
      time: 2022
    right:
      - text: äº¬ICPå¤‡1905135å·
        link: https://beian.miit.gov.cn/#/Integrated/index


# ä¾§è¾¹æ  (aside)
# --------------------------------
aside:
  enable: true
  button: true
  mobile: true # æ‰‹æœºæ˜¾ç¤º
  position: right # å·¦è¾¹å³è¾¹ right/left
  card_author:
    enable: true
    description: <div class="author-info__description"></div>è¿™æœ‰å…³äº<b>äº§å“ã€è®¾è®¡ã€å¼€å‘</b>ç›¸å…³çš„é—®é¢˜å’Œçœ‹æ³•ï¼Œè¿˜æœ‰<b>æ–‡ç« ç¿»è¯‘</b>å’Œ<b>åˆ†äº«</b>ã€‚<div class="author-info__description2"></div>ç›¸ä¿¡ä½ å¯ä»¥åœ¨è¿™é‡Œæ‰¾åˆ°å¯¹ä½ æœ‰ç”¨çš„<b>çŸ¥è¯†</b>å’Œ<b>æ•™ç¨‹</b>ã€‚
    button:
      link: /about/
      icon: fas fa-circle-chevron-right
      text: äº†è§£æ›´å¤š
    social:
      - title: Dribbble
        icon: fab fa-dribbble
        link: https://dribbble.com/zhheo
      - title: Github
        icon: fab fa-github
        link: https://github.com/zhheo
  card_weixin:
    enable: true
    face: https://p.zhheo.com/202363e5ca73123f202bbeda6f024866a181080502.png!cover
    backFace: https://p.zhheo.com/202309da537f19ad4992f1340e53a11098df081402.png!cover
  card_recent_post:
    enable: false
    limit: 5 # è¾“å…¥0å…¨æ˜¾ç¤º
    sort: date # æ˜¾ç¤ºå‘å¸ƒæ—¥æœŸ/æ›´æ–°æ—¥æœŸ
    sort_order: 
  card_all_info:
    enable: true
    post_count: true
    runtime: true
    word_count: false

# å·¥å…· (tool)
# --------------------------------

# å¹¿å‘Š (ad)
# ad:
#   index:
#   aside:
#   post:

# åŠ è½½åŠ¨ç”» (loading)
loading: 
  enable: true

# æ‰‹æœºè¾¹æ  (sidebar)
sidebar: 
  list_group: true
  tag: true

# ä¸­æ§å° (console)
console:
  comment: true
  tag: true
  archives: true 

# å›¾ç‰‡ç¯ç®± (fancybox)
# http://fancyapps.com/fancybox/3/
fancybox: true

# æ ‡ç­¾å¤–æŒ‚ (mermaid)
mermaid:
  enable: false
  # ä¸»é¢˜: default/forest/dark/neutral
  theme:
    light: default
    dark: dark

# æ ‡ç­¾ (Note)
note:
  style: flat
  icons: true
  border_radius: 3
  light_bg_offset: 0

# å¤–æŒ‚æ ‡ç­¾ (tag)
tag:
  biliapi: https://api.320.ink/api/b?id=

# æ˜¾ç¤ºæ¨¡å¼ (display mode)
display_mode: light #light/dark

# ç½‘å€è¿è¡Œæ—¶é—´ (runtime)
runtime:
  enable: true
  time: "2023/02/08 00:00:00"

# åœç®—å­ (busuanzi) 
busuanzi:
  site_uv: true
  site_pv: true
  page_pv: true


# å³ä¸‹æ‚¬æµ®æ  (right side)
# --------------------------------

rightside_item_order:
  enable: false
  hide: 
  show: 
# ç®€ä½“ç¹ä½“åˆ‡æ¢
translate:
  enable: true
  default: ç¹
  defaultEncoding: 2
  translateDelay: 0
  msgToTraditionalChinese: 'ç¹'
  msgToSimplifiedChinese: 'ç°¡'

# é˜…è¯»æ¨¡å¼
readmode: false

# æ·±è‰²æ¨¡å¼
darkmode:
  enable: true
  button: true
  # è‡ªåŠ¨åˆ‡æ¢æš—/äº®æ¨¡å¼
  # 1ï¼š æŒ‰ç…§ç³»ç»Ÿè®¾ç½®ï¼Œå¦‚æœç³»ç»Ÿä¸æ”¯æŒæ·±è‰²æ¨¡å¼ï¼Œå®ƒå°†åœ¨ä¸‹åˆ 6 ç‚¹åˆ°æ—©ä¸Š 6 ç‚¹ä¹‹é—´åˆ‡æ¢æ·±è‰²æ¨¡å¼
  # 2ï¼š åœ¨ä¸‹åˆ 6 ç‚¹åˆ°æ—©ä¸Š 6 ç‚¹ä¹‹é—´åˆ‡æ¢é»‘æš—æ¨¡å¼
  autoChangeMode: 1

# Pjax
# å®ƒå¯èƒ½åŒ…å«é”™è¯¯å’Œä¸ç¨³å®š
# https://github.com/MoOx/pjax
pjax:
  enable: true
  exclude:
    # - xxxx
    # - xxxx

# Aplayer
aplayerInject:
  enable: false
  per_page: true


# å¼¹çª— (snackbar)
# https://github.com/polonel/SnackBar
# ä½ç½® top-left / top-center / top-right / bottom-left / bottom-center / bottom-right
snackbar:
  enable: true
  position: top-center
  bg_light: '#49b1f5' 
  bg_dark: '#1f1f1f' 

# é¢„åŠ è½½ (instantpage)
# https://instant.page/
instantpage: true

# ä¸­è‹±æ–‡é—´åŠ ç©ºæ ¼ (pangu)
pangu:
  enable: false
  field: site # site/post

# å›¾ç‰‡æ‡’åŠ è½½ (lazyload)
# https://github.com/verlok/vanillsa-lazyload
lazyload:
  enable: false
  field: site # site/post
  placeholder:
  blur: false

# 51la
# https://v6.51.la/
la:
  enable: false
  id: JduKh41OtkNBcW5g

# ç™¾åº¦éªŒè¯
baidu:
  enable: false
  id: 828db1fd637f3717a876af84bf0678bd

# é¢„åŠ è½½ (preconnect)
preconnect:
  - //bu.dusays.com
  - //d.zhheo.com
  - //p.zhheo.com
# PWA
# https://github.com/JLHwung/hexo-offline
pwa:
  enable: false
  manifest: /pwa/manifest.json
  apple_touch_icon: /pwa/apple-touch-icon.png
  favicon_32_32: /pwa/32.png
  favicon_16_16: /pwa/16.png
  mask_icon: /pwa/safari-pinned-tab.svg


# å¼•å…¥ (inject)
# --------------------------------
inject:
  head:
    # CSS
    # - <link rel="stylesheet" href="/xxx.css">
    - <link rel="stylesheet" href="https://cdn3.codesign.qq.com/icons/X2bzpZvRWkZkAaV/latest/iconfont.css">
    - <link rel="stylesheet" href="https://lf6-cdn-tos.bytecdntp.com/cdn/expire-1-M/Swiper/8.0.6/swiper-bundle.min.css">
    - <script>var meting_api = "https://meting.zhheo.com/?server=:server&type=:type&id=:id&auth=:auth&r=:r";</script>
  bottom:
    # JS
    # - <script src="/js/xxx.js"></script>

    

# CDN
# --------------------------------
CDN:
  #ä¸»é¢˜CDN
  # å¯é€‰local/jsdelivr/unpkg/cdnjs/custom
  internal_provider: local

  # ç¬¬ä¸‰æ–¹CDN
  # å¯é€‰moezz/local/jsdelivr/unpkg/cdnjs/custom/tianli(éœ€è¦å¾å¾—tianliæœ¬äººåŒæ„)/elemecdn
  third_party_provider: tianli

  version: false
  # Custom format
  # å®ä¾‹: https://cdn.staticfile.org/${cdnjs_name}/${version}/${min_cdnjs_file}
  custom_format:

  option:
    # main_css:
    # main:
    # utils:
    jquery: https://lf6-cdn-tos.bytecdntp.com/cdn/expire-1-M/jquery/3.6.0/jquery.min.js
    heo: /js/heo.js
    # countup_js: /js/countup.js
    # translate:
    # local_search:
    algolia_js: /lib/algolia/algolia.js
    # algolia_search_v4: 
    instantsearch_v4: /lib/algolia/instantsearch.min.js
    # pjax:
    twikoo: https://cdn1.tianli0.top/gh/zhheo/twikoo@dev/dist/twikoo.all.min.js
    # waline_js:
    # waline_css:
    # mathjax:
    # katex:
    # katex_copytex:
    # mermaid:
    lazyload: https://lf3-cdn-tos.bytecdntp.com/cdn/expire-1-M/vanilla-lazyload/17.3.1/lazyload.iife.min.js
    instantpage: https://lf3-cdn-tos.bytecdntp.com/cdn/expire-1-M/instant.page/5.1.0/instantpage.min.js
    # typed:
    # pangu:
    pace: https://lf6-cdn-tos.bytecdntp.com/cdn/expire-1-M/pace/1.2.4/pace.min.js
    qrcode: /lib/qrcode/qrcode.min.js
    fancybox_css_v4: https://cdn1.tianli0.top/npm/@fancyapps/ui/dist/fancybox.min.css
    # fancybox_v4:
    snackbar_css: https://lf3-cdn-tos.bytecdntp.com/cdn/expire-1-M/node-snackbar/0.1.16/snackbar.min.css
    snackbar: https://lf6-cdn-tos.bytecdntp.com/cdn/expire-1-M/node-snackbar/0.1.16/snackbar.min.js
    # activate_power_mode:
    fontawesomeV6: https://cdn1.tianli0.top/npm/@fortawesome/fontawesome-free/css/all.min.css
    aplayer_css: https://lf6-cdn-tos.bytecdntp.com/cdn/expire-1-M/aplayer/1.10.1/APlayer.min.css
    aplayer_js: https://lf26-cdn-tos.bytecdntp.com/cdn/expire-1-M/aplayer/1.10.1/APlayer.min.js
    meting_js: https://cdn1.tianli0.top/gh/hexo-theme-Acrylic/JS-Acrylic@main/Meting.js
    # artalk_js:
    # artalk_css: